### ISSUE TITLE
Home Page (Functions) 

### ISSUE THREAD

**Issue by Felix-Deng** [UofT-VEEP/VEEP-Website#36]
### Summary 
This is the sub issue under Home Page to improve the functionalities of the Home Page of the website. 

### For Sub-Issue
  
 - Change Proposal 
	 1. Change project types into Card and Button 
	 2. Propose and add changes to the website to improve usability and interaction 

- Deadline of the task: TBD 

- Additional Info

**Comment by CatherineZM** [comment]
Closing issue to combine it with UI
