### ISSUE TITLE
Projects Page (Functions) 

### ISSUE THREAD

**Issue by Felix-Deng** [UofT-VEEP/VEEP-Website#47]
### Summary
This is the sub issue under Projects Page to add functions to the webpage 

### For Sub-Issue
  
 - Change Proposal 
	 1. For upcoming projects (you can only make a testing section), add buttons for people to apply to roles 
	 2. Link technical managers' introduction to their contact information (current projects only) 

- Deadline of the task: TBD 

- Additional Info

**Comment by CatherineZM** [comment]
Closing issue to combine it with UI
